### ISSUE TITLE
predicate value in opslevel_check_service_property doesn't accept any interpolation nor references

### ISSUE THREAD

**Issue by ricoli-motorway** [OpsLevel/terraform-provider-opslevel#496]
# Summary
I think there's an issue with the validation of the https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/resources/check_service_property resource, as it's not allowing any sort of references or interpolation in the `value` of a predicate of type `satisfies_jq_expression`. This prevents us from using interation to create such resources, leading to unnecessary repetition that increases maintenance effort.

# Examples
Both examples were ran using the latest version of the provider at time of writing - 1.3.0

## Reference
```
locals {
  example_checks = {
    first = {
      level = local.rubric_levels.gold.id
      predicate = {
        value = ".first == 0"
      }
    }
    second = {
      level = local.rubric_levels.silver.id
      predicate = {
        value = ".second == 0"
      }
    }
}

resource "opslevel_check_service_property" "example_checks" {
  for_each = local.example_checks

  name     = "${each.key} example check"
  enabled  = true
  owner    = <some team reference here>
  category = <some category id here>
  level    = each.value.level
  property = "custom_property"

  property_definition = <some property definition>

  predicate = {
    type  = "satisfies_jq_expression"
    value = each.value.predicate.value
  }
}
```
Which results in this error when running a plan:
```
│  158:   predicate = {
│  159:     type  = "satisfies_jq_expression"
│  160:     value = each.value.predicate.value
│  161:   }
│ 
│ Predicate type 'satisfies_jq_expression' requires a value
```

## String interpolation
```
locals {
  example_checks = {
    first = {
      level = local.rubric_levels.gold.id
    }
    second = {
      level = local.rubric_levels.silver.id
    }
}

resource "opslevel_check_service_property" "example_checks" {
  for_each = local.example_checks

  name     = "${each.key} example check"
  enabled  = true
  owner    = <some team reference here>
  category = <some category id here>
  level    = each.value.level
  property = "custom_property"

  property_definition = <some property definition>

  predicate = {
    type  = "satisfies_jq_expression"
    value = ".${each.key} == 0"
  }
}
```
Which results in this error when running a plan:
```
│  146:   predicate = {
│  147:     type  = "satisfies_jq_expression"
│  148:     value = ".${each.key} == 0"
│  149:   }
│ 
│ Predicate type 'satisfies_jq_expression' requires a value
```

## Missing test cases
I can see that there's no test case covering this scenario - the only predicate type being tested seems to be "exists" as per https://github.com/OpsLevel/terraform-provider-opslevel/blob/main/tests/check_service_property.tftest.hcl#L9-L12

**Comment by davidbloss** [comment]
👋 Hi @ricoli-motorway, thank you for raising this issue! Writing more complete tests (that would have caught this) is definitely in our backlog. We have merged in a fix to this validation bug which will be rolled into our next release - planned for Friday, Oct 11th

**Comment by ricoli-motorway** [comment]
Hi @davidbloss! I have just bumped into this same issue when using the latest version of the provider at time of writing (1.3.4), so it seems it wasn't quite fixed? I'm running the same code as per my original issue description.

```
│  159:   predicate = {
│  160:     type  = "satisfies_jq_expression"
│  161:     value = ".${each.key} == 0"
│  162:   }
│ 
│ Predicate type 'satisfies_jq_expression' requires a value
```
